config/routes.rb
MyAppV40::Application.routes.draw do
  resources :wishes
  devise_for :users
  get "about", to: 'pages#about'
  get "contacts", to: "pages#contacts"
  get "pages/infos"
  get "gallery", to: "pages#gallery"
  resources :news
  resources :prices
  

   root 'pages#index'

  

end

app/models/news.rb
class News < ActiveRecord::Base
  extend FriendlyId
    friendly_id :title, use: [:slugged, :history]
    
  mount_uploader :image, ImageUploader
  
  validates :title, :description, presence: true
  validates :title, uniqueness: true
  
  
    
    def should_generate_new_friendly_id?
        new_record?
      end
end

app/models/price.rb
class Price < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
 after_create :send_mail
 
 def send_mail
   UserMailer.post_email(self.email).deliver
   end  
       
       
       end

app/models/wish.rb
class Wish < ActiveRecord::Base
  
  validates :title , :text, presence: true
  validates :title, uniqueness: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:show, :index]
  # GET /news
  # GET /news.json
  def index
    @news = News.paginate(:page => params[:page],:per_page => 5).order('id DESC')
  end
  
  # GET /news/1
  # GET /news/1.json
  def show
    if request.path != news_path(@news)
        redirect_to @news, status: :moved_permanently
      end
  end

  # GET /news/new
  def new
    if current_user.admin?
    @news = News.new
  else redirect_to root_path
  end
  end

  # GET /news/1/edit
  def edit
    if current_user.admin?
    else redirect_to root_path
    end
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        flash[:success]  = 'Новость успешно добавлена!'
        format.html { redirect_to root_path }
        format.json { render action: 'index', status: :created, location: @news }
      else
        format.html { render action: 'new' }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        flash[:success] = 'Новость успешно обновлена!'
        format.html { redirect_to root_path }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    if current_user.admin?
    @news.destroy
    flash[:success] = 'Новость удалена!'
    redirect_to root_path
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.friendly.find(params[:id])
      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :image, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contacts
  end
  
  def index
    @news = News.limit(4).order('id DESC')
    @wishes = Wish.all
    @price1 = Price.find(2)
    @price2 = Price.find(3)
    @price3 = Price.find(4)
    @price_vip = Price.find(1)
  end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_prices, only: [:edit,:update,:show] 
def index
if current_user.try(:admin?)
 @prices = Price.all
 else
 redirect_to root_path
 end
end

def show
if current_user.try(:admin?)
  else
  redirect_to root_path	
  end
end

def new
if current_user.try(:admin?)
  @price = Price.new
  else
  redirect_to root_path
  end
end

def create
  @price = Price.new(prices_params)
  if @price.save
    redirect_to root_path
  else
    render action: 'new'
  end
end

def edit
	if current_user.try(:admin?)
	else
	redirect_to root_path
	end
end

def update
  if @price.update(prices_params)
    flash[:success] = 'Цена успешно обновлена!'
    redirect_to root_path
  else
    render action: 'edit'
  end
end

  private
  
    def prices_params
      params.require(:price).permit(:title, :description, :cost)
    end
    
    def set_prices
      @price = Price.find(params[:id])
    end
    
  
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  before_action :set_wish , only: [:show,:edit,:update,:destroy]
  before_filter :authenticate_user!

def index
  if current_user.admin?
  @wishes = Wish.all.order('id DESC')
else 
  redirect_to root_path
end
end

def show
  if current_user.admin?
    @wish = Wish.find(params[:id])
  else
    redirect_to root_path
  end
end

def new
  @wish = Wish.new
end

def edit
  if current_user.admin?
    @wish = Wish.find(params[:id])
  else
    redirect_to root_path
  end
end

def create
  @wish = Wish.new(wish_params)
    respond_to do |format|
      if @wish.save
        flash[:success] = 'Спасибо Вам!Мы рассмотрим ваше пожелание!'
        format.html { redirect_to root_path }
        format.json { render action: 'index', status: :created, location: @wish }
      else
        format.html { render action: 'new' }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
end

def update
  respond_to do |format|
    if @wish.update(wish_params)
      format.html { redirect_to root_path, success: 'Wish was successfully updated.' }
      format.json { head :no_content }
    else
      format.html { render action: 'edit' }
      format.json { render json: @wish.errors, status: :unprocessable_entity }
    end
  end
end


def destroy
    @wish.destroy
    redirect_to root_path
    flash[:success] = 'Пожелание удалено из списка!'
end

private

def wish_params
  params.require(:wish).permit(:title, :text, :complete)
end

def set_wish
  @wish = Wish.find(params[:id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def flash_class(level)
    case level
      when :notice then "alert alert-success"
      when :success then "alert alert-success"
      when :error then "alert alert-danger"
      when :alert then "alert alert-danger"
        
  end
end

    def full_title(page_title)
      base_title = 'Playstation3 club'
      if page_title.empty?
        base_title
      else
        "#{base_title} | #{page_title}"
    end
  end
  
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_alerts.html.erb
<div>
	<% flash.each	do |key,value|%>
		<div class="<%= flash_class(key)%> fade in">
			<a href	="#"data-dismiss = "alert" class="close">&times</a>
			<%= value %>
			</div>
			<%end%>

app/views/layouts/_footer.html.erb
<div class = 'row'>
<div class = 'col-lg-12 col-md-12 col-xs-12 col-sm-12 footer'>
<h5 class = 'text-center'>©PS3club 2013</h5>
<div class = 'col-lg-4 col-md-4 col-sm-4 col-xs-12 tags'><p class = 'tags-footer'>Облако тегов</p>
<p>playstation3 PS3 playstation </p>
<p>ps3club playstation club psclub</p>
<p>playstation харьков клуб </p>
<p>псклуб пс3клуб psclub kharkov</p>
<p>консоль консольный клуб </p>
<p>игры харьков игротека</p>
</div>


<div class = 'col-lg-4 col-md-4 col-xs-12 col-sm-4 contacts'>
<p class = 'tags-footer'>Контакты</p>
<p>(097)-62-192-13</p><p> (063)-789-58-98</p><p>Харьков</p><p>Тринклера 24</p>
</div>


</div>
</div>

app/views/layouts/_google.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44897296-1', 'psclub.kh.ua');
  ga('send', 'pageview');

</script>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse navbar-static-top topnavbar mynav">
  <div class="container">
    <div class="row">
        
  <div class="col-lg-4 col-sm-4 vklogo">
  <h2><%= image_tag 'vk-02.png',width: 30%><%= link_to 'vk.com/psclub_kh', 'http://vk.com/psclub_kh' %></h2>
    </div>
    <div class = 'col-lg-4 col-sm-4 logo'>
    <h2><%= link_to 'PS3club', root_path %></h2>
    </div>
    
  <div class="col-lg-4 col-sm-4 telephones">
    <h3>Тринклера 24</h3>
  
  <h2>
  097-62-192-13</h2>
  <h2>063-789-58-98
  </h2>
  </div>
  </div>
  
      </div>
</div>


<div class="header-middle">
    <a href=""  title="Playstation3 club харьков" alt=" "><div class="fb"><span aria-hidden="true" class="icon-facebook"></span></div></a> 
    <a href="" title="psclub kharkov псклуб" alt="псклуб playstation"><div class="gpl"><span aria-hidden="true" class="icon-google-plus"></span></div></a>
    <a href=""  title="ps3club харьков" alt="playstation kharkov"><div class="vk"></div></a>
    <a href=""  title="ps3 playstation club"><div class="xz"><span aria-hidden="true" class="icon-feed"></span></div></a>
    <a href="" title="psclub ps3club" alt="psclub ps3club псклуб"><div class="tw"><span aria-hidden="true" class="icon-twitter"></span></div></a>       
  </div>
<!-- Fixed navbar -->
   <div class="navbar navbar-inverse navbar-static-top">
     <div class="container">
       <div class="navbar-header">
         <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
       </div>
       <div class="navbar-collapse collapse">
         <ul class="nav navbar-nav ">
         <li><%= link_to 'Главная' , root_path, class: 'icon-home2' %></li>
         <li><%= link_to 'Новости' , news_index_path, class: 'icon-blog'%></li>
         <li><%= link_to 'О нас', about_path, class:'icon-rocket'%></li>
         <li><%= link_to 'Контакты', contacts_path, class: 'icon-location2' %></li>
         <% unless current_user.try(:admin?)%>
         <li><%= link_to 'Пожелание', new_wish_path, class: 'icon-envelop'  %></li>
         <%end%>
         <% if current_user.try(:admin?) %>
         <li><%= link_to 'Пожелание', wishes_path, class: 'icon-envelop' %></li>
         <%end%>
         
                    </ul>
               </div><!--/.nav-collapse -->
     </div>
   </div>

app/views/layouts/_side_col.html.erb
<div class = 'col-3 col-lg-3 col-md-4 col-sm-12 col-xs-12 side_index_col'>
<h2>Последние новости</h2>
<ul class = 'ca-menu'>

<% @news.each do |news| %>

<li>
 <span class='ca-icon'>A</span>
 <%= link_to '', news%>

 <div class = 'ca-content'>	
 <h2 class='ca-main'><%= truncate news.title, length: 30 %></h2>
 <h5 class='ca-sub'><%= truncate(strip_tags(news.description), length: 100) %></h5>
</div>

</li>
<%end%>

</ul>
<script type="text/javascript" src="//vk.com/js/api/openapi.js?101"></script>

<!-- VK Widget -->
<div id="vk_groups"></div>
<script type="text/javascript">
VK.Widgets.Group("vk_groups", {mode: 0, width: "300", height: "350", color1: 'FFFFFF', color2: '2B587A', color3: '5B7FA6'}, 60183195);
</script>
<div class= 'side_login'>
<% if user_signed_in? %>
<h2 class="text-center">Добро пожаловать</h2>
<h3 class="text-center">Вы вошли как <strong><%= link_to current_user.email, user_registration_path%></strong></h3>
<h3 class = 'text-center'><%= link_to 'Добавить новость', new_news_path if current_user.admin?%></h3>
<h3 class = 'text-center'><%= link_to 'Изменить цены', prices_path if current_user.admin?%></h3>
<h3 class = 'text-center'><%= link_to 'Выйти' , destroy_user_session_path , :method => :delete if user_signed_in?%></h3>

<% else %>
<p class="text-center"><%= link_to 'Вход', new_user_session_path%></p>
<%end%>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<script src="http://vk.com/js/api/openapi.js" type="text/javascript"></script>
	
	<%= metamagic %>
  
	<%= render 'layouts/google.html.erb'%>
  <title><%= full_title(yield(:title))%></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Playstation3 клуб playstation 3 club псклуб харьков игровой клуб консоль консольный пс клуб playstation3">
  <meta name="author" content="">

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= tinymce_assets %>
  <%= favicon_link_tag('ps3logo.png')%>

 <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700&subset=latin,cyrillic-ext,cyrillic' rel='stylesheet' type='text/css'>
 <link href='http://fonts.googleapis.com/css?family=Droid+Sans:regular,bold' rel='stylesheet' type='text/css'/>
  <%= csrf_meta_tags %>
  <%= render 'layouts/google.html.erb'%>
</head>

<body>
<%= render 'layouts/alerts' %>		
<%= render 'layouts/navbar' %>


<%= yield %>
<%= render 'layouts/footer.html.erb' %>

<%= render 'layouts/google.html.erb'%>
</body>
</html>

app/views/layouts/metrica.html.erb
<!-- Yandex.Metrika informer -->
<a href="http://metrika.yandex.ru/stat/?id=22847602&amp;from=informer"
target="_blank" rel="nofollow"><img src="//bs.yandex.ru/informer/22847602/3_1_FFFFFFFF_EFEFEFFF_0_pageviews"
style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" onclick="try{Ya.Metrika.informer({i:this,id:22847602,lang:'ru'});return false}catch(e){}"/></a>
<!-- /Yandex.Metrika informer -->

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter22847602 = new Ya.Metrika({id:22847602,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/22847602" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

app/views/news/_form.html.erb
<div class = 'row'>
	<div class = 'col-lg-10'>
		<div class = 'panel panel-success'>
			<div class = 'panel-heading'>Добавить новость</div>
			<div class = 'panel-body'>
			
		
<hr>
<%= form_for @news, :html => {:multipart => true} do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-lg-4">
    <%= f.label "Заголовок" %><br>
    <%= f.text_field :title , class: "form-control"%>
  </div>
  <div class="col-lg-10">
  <%= f.label 'Текст для новости'%>	
<%= f.text_area :description, :class => "tinymce" %>

<%= tinymce :description %>
</div>
    <p>
      <div class = "col-lg-10">
	<label>Добавить изображение
      <%= f.file_field :image %>
      <%= f.hidden_field :image_cache  %>
      </div>
    </p>
  <div class="col-lg-4">
    <%= f.submit 'Добавить', class: 'btn btn-success'%>
  </div>

<% end %>



</div>

app/views/news/edit.html.erb
<p class="lead">Редактировать новость</p>

<%= render 'form' %>
<p></p>
<%= link_to 'Назад', news_index_path, class: 'btn btn-default' %>
<br>
<hr>
<%= link_to 'Удалить', @news , method: :delete, data: {confirm: "Удалить эту новость?"},class: 'btn btn-danger btn-sm' if current_user.try(:admin)%></br>
<i class = "text-muted"> Удалить новость <i></p>

app/views/news/index.html.erb
<%= render 'layouts/google.html.erb'%>
<%= provide(:title, ('Новости'))%>

<%= render 'layouts/side_col'%>

<div class = 'row'>

	<div class="col-md-7 col-lg-8 col-xs-12 col-sm-12 news_col">
		<h2>Новости</h2>
		<hr>
    <% @news.each do |news| %>
			    <%=link_to (image_tag news.image_url(:thumb).to_s, class:'img-responsive'), news %>			  			
			    <p class = "text-muted small"><%= I18n.localize(news.created_at,:format => :short)%></p>
				
     <h4><%= link_to truncate(news.title, length: 100),news %></h4>
    <p><%=   truncate (strip_tags news.description),length:300, omission: ("...") %></p>
		 <p><%= link_to 'Редактировать', edit_news_path(news), class: 'text-warning' if current_user.try(:admin)%></p>
		<p class = "text-right"> <%= link_to 'Читать полностью', news_path(news) %></p>
		<hr>
        <% end%>
        	<ul class = 'text-center'>	<%= will_paginate @news, class: 'apple-pagination'%></ul>
        
        		</div>
        

</div>

app/views/news/new.html.erb
<%= render 'form' %>

<%= link_to 'Назад', news_index_path, class: 'btn btn-default' %>

app/views/news/show.html.erb
<%= render 'layouts/google.html.erb'%>
<%= provide :title, @news.title  %>
<div class="container">
	<div class = 'col-md-12 col-lg-12 col-xs-12 col-sm-12 news_show'>
		<h2><%= @news.title%></h2>
		<hr>
		
	<%= image_tag (@news.image_url(:show)).to_s, class: 'img img-rounded img-responsive imgshow'%>
			</br>
			<p> <%= raw @news.description%> </p>
				<%= link_to 'Удалить', @news, method: :delete, data: {confirm: "Удалить эту новость?"},class: 'btn btn-danger' if current_user.try(:admin)%>
				<%= link_to 'Редактировать', edit_news_path(@news),class: 'btn btn-warning' if current_user.try(:admin) %> 
				<%= link_to 'Назад', news_index_path,class: "btn btn-default" %>
			</div>	
</div>

app/views/pages/about.html.erb
<%= render 'layouts/google.html.erb'%>
<%= provide :title, 'О нас'%>

<div id = 'about'>
	<div class = 'container'>
	<div class = 'row'>
	
		<div class = 'col-sm-12 col-lg-12'>
		
			<h2>О нас</h2>
			<hr>
		
		</div>
		
		<div class = 'col-sm-12 col-lg-12 about_head'>
			<h3>Первый в Харькове</h3>
			<h1>Playstation3 Club</h1>
			<hr>
		</div>
		
			<div class="col-lg-6 col-sm-6 about_content_left">
				<h1>Огромный V.I.P зал</h1>	
				 <h3>диагональ экрана 2.5м!</h3>
				 <%= image_tag('vip.jpg', class: 'img-responsive')%>
			</div>
			
			<div class = 'col-lg-6 col-sm-6 about_content_right'>
				<h1>7 комнат эклюзивного дизайна</h1>
				<h3>40" - 46" плазменные телевизоры</h3>
				<h3>объемный звук</h3>
				<%= image_tag('auto.png',class:'img-responsive')%>
				<%= image_tag('boxing.png',class:'img-responsive')%>
				
			</div>
		
	
	</div>
	
	<div class = 'row'>
		
		
		<div class = 'col-lg-6 col-sm-6 about_content_2_left'>
		
			<h1>Мы расположены в самом центре города</h1>
		    <%= image_tag('strelka.jpg', class: 'img-responsive')%>
		</div>
		<div class = 'col-lg-6 col-sm-6 about_content_2_right'>
		
			<h1>Комфортные игровые комнаты</h1>
			<h3>самые новые игровые приставки</h3>
			<%= image_tag('gamers.jpg', class: 'img-responsive')%>
		
		</div>
		
	</div>
	
	</div>
	
</div>

app/views/pages/contacts.html.erb
<%= render 'layouts/google.html.erb'%>
<%= provide :title , 'Контакты'%>
<div id =  'contacts'>
	<div class = "row">
	<div class = 'col-md-12 col-lg-12 col-sm-12 contact_title'>
			<h1>Контакты</h1>
			<hr>		
			</div>
					<div class = 'col-lg-4 col-md-4 col-xs-4 col-sm-4 contacts_col'>
				
<address class="contact">
	<strong>PlayStation3 Club </strong> </br>
	Ул.Тринклера,24</br>
	Харьков.Украина</br>
	</p>
	(097)-62-192-13;<p> (063)-789-58-98; </p>
	<strong>Vkontakte:</strong> <%= link_to 'vk.com/psclub_kh', 'http://vk.com/psclub_kh' %>
	</address>
	</div>
<div class="col-md-8 col-sm-8 col-lg-8 col-xs-8 contact_map">		
<script type="text/javascript" charset="utf-8" src="//api-maps.yandex.ru/services/constructor/1.0/js/?sid=xryE3opugfnoQbSGOHV_p_OyIJt-TTn4&width=800&height=350"></script>
</div>
</span>
</div>
</div>

app/views/pages/gallery.html.erb
<%= render 'layouts/google.html.erb'%>
<%= provide :title, 'Галерея'%>
	<h1 class = 'myh1'> Галерея <p>PSCLUB в харькове представляет</p></h1>
<div class = 'container custom_container'>
	<div class = 'otstup'></div>
	
	<div class = 'row upper_images'>
		
		<div class = ' col-md-7 col-xs-7  '><%= image_tag('kepka.png', class: 'img-responsive')%></div>
		<div class = 'col-md-5 col-xs-5'><%= image_tag('vihod.png', class: 'img-responsive')%></div>

		</div><!-- ROW-->
	<div class = 'otstup'></div>
	<div class = 'row rooms'>
	<div class = 'col-md-4  col-xs-4'><%= image_tag('auto.png', class: 'img-responsive') %></div>
	<div class = 'col-md-4  col-xs-4'><%= image_tag('autograph.png', class: 'img-responsive') %></div>
	<div class = 'col-md-4  col-xs-4'><%= image_tag('basket.png', class: 'img-responsive') %></div>
	<div class = 'col-md-4  col-xs-4'><%= image_tag('bike.png', class: 'img-responsive') %></div>
	<div class = 'col-md-4  col-xs-4'><%= image_tag('boxing.png', class: 'img-responsive') %></div>
	<div class = 'col-md-4  col-xs-4'><%= image_tag('football.png', class: 'img-responsive') %></div>
	
	
	
	
	
	</div><!-- ROW2-->
	<div class = 'otstup'></div>
   	<div class = 'row down_images'>
		<div class = 'col-md-6  col-xs-6'><%= image_tag('graffity.png',class: 'img-responsive')%></div>
		<div class = 'col-md-6 col-xs-6'><%= image_tag('dver.png',class: 'img-responsive')%></div>
   	</div><!--ROW3-->
	
	
</div> <!--CONTAINER-->


<!-- MOBILE-XS DEVISES-->

app/views/prices/edit.html.erb
<%= render 'form' %>

app/views/prices/index.html.erb
<div class = 'row'>
<% @prices.each do |pr| %>
<div class = 'col-md-3 col-sm-3 col-xs-3 col-lg-3 price_col'>
<h5><%= pr.title%></h5>
<p><%= pr.description %></p>
<p><%= pr.cost %>грн\час </p>
<p> <%= link_to 'Редактировать', edit_price_path(pr) %></p>
</div>

<% end %>
</div>

app/views/prices/new.html.erb
<%= render 'form' %>

app/views/users/shared/_links.erb
<div class="sharedlinks">
<%- if controller_name != 'sessions' %>
  <p class = "text-muted"> Уже есть аккаунт? <%= link_to "Войти", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <p class="text-muted">Присоединяйся! <%= link_to "Регистрация", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
 <p class="text-muted"> Забыли пароль? <%= link_to "Восстановить пароль", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>
</div>

app/views/wishes/show.html.erb
<%= provide :title , @wish.title%>
<div class = 'row'>
	<div class = 'col-lg-8 col-md-8 col-xs-8'>
		<div class = 'panel panel-success'>
			<div class = 'panel-heading lead text-center'><%= @wish.title%></div>
			<div class = 'panel-body'>
				<p class = 'text-center'><%= @wish.text  %></p>
				
				<%= button_to 'Выполнено' , @wish, method: :delete, data: {confirm: "Вы действительно выполнили это пожелание?"},class: 'btn btn-success btn-sm'%></p>
				<%= button_to 'Удалить' , @wish, method: :delete, data: {confirm: "Удалить это пожелание?"},class: 'btn btn-danger btn-sm'%></p>
				<%= link_to 'назад', wishes_path %>
				</div>
			</div>
		</div>
	</div>